### ISSUE TITLE
stdin left in raw state after crash

### ISSUE THREAD

**Issue by stevedonovan** [GeertJohan/go.linenoise#3]
Not sure this is really a bug for go-linenoise, but if one has an uncontrolled panic then `stdin` is left in raw mode, messing up the terminal.  Maybe simply warn about this possibility?

**Comment by GeertJohan** [comment]
Yes, I have had this problem several times.. But I dont think there is a way for go.linenoise to recognize the panic and switch back. Maybe it would be possible to hijack the stdout.. but to do anything useful with that would require changes to the linenoise C code.

**Comment by stevedonovan** [comment]
Yes, I imagine it would be a problem with any linenoise binding. Unfortunately catching the panic does not itself solve the problem.  

But I have discovered the Linux command `reset` ;)

**Comment by GeertJohan** [comment]
I'm closing this issue. If you believe it is still a problem please open an issue at the linenoise project.
