### ISSUE TITLE
completion handler should contain cursor position

### ISSUE THREAD

**Issue by elazarl** [GeertJohan/go.linenoise#5]
Note that in the C version of linenoise, the callback can get the cursor position.

This is curcial in order to implement completion correctly.

**Comment by GeertJohan** [comment]
Are you working on a fix for this?

**Comment by elazarl** [comment]
Not yet, but if you want, I'll do that.

**Comment by GeertJohan** [comment]
Yes, you're welcome to add this functionality and create a PR :+1: 
Please make sure though that existing outline isn't changed. I don't want to break existing imports.

**Comment by elazarl** [comment]
It seems that linenoise.c itself lack support for that.
